# Lab Assignment 8 # 

- Numpy stands for numerical python, it is an open soruce python array processing library used for data analysis and scientific computing with python.
- Numpy arrays are faster and more compact than python lists.
- an array consumes less memory and is convinient to use 
- numpy array are multidimensional while lists are one dimensional

In [4]:
import numpy as np 

arr = np.array([1,2,3,4,5])
print ("ond-D array", arr)
print(type(arr))

ond-D array [1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimension ##
The dimension is being calculated by the 'ndim' method on the basis of the no. of square brackets

In [7]:
import numpy as np

arr2 = np.array([[1,2,3],[4,5,6]])
print("one-D array", arr2)
print(type(arr2))
print("Dimension:",arr2.ndim)

one-D array [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Dimension: 2


## Data Type ##
The data type used in the array is being reflected using '.dtype' command

In [10]:
import numpy as np

arr3 = np.array([(1,2,3)])
print(arr3)
print(type(arr3))
print(arr3.dtype)

[[1 2 3]]
<class 'numpy.ndarray'>
int64


In [11]:
import numpy as np

arr3 = np.array([(1.12, 2.23, 3.6)])
print(arr3)
print(type(arr3))
print(arr3.dtype)


[[1.12 2.23 3.6 ]]
<class 'numpy.ndarray'>
float64


## Converting Data Type ##
Here we are converting the data types using '.astype' 

In [12]:
import numpy as np

arr3 = np.array([(1.12, 2.23, 3.6)])
ar = arr3.astype(int)
print("Modified Array Data: ", ar)
print(type(ar))
print(ar.dtype)
print(arr3)
print(type(arr3))
print(arr3.dtype)


Modified Array Data:  [[1 2 3]]
<class 'numpy.ndarray'>
int64
[[1.12 2.23 3.6 ]]
<class 'numpy.ndarray'>
float64


## Displaying the data type of String ##
In this we are displaying the data type of string which shows the max length of the string and is displayed as '<U'

In [15]:
import numpy as np

arr4 = np.array(['Naman', 'Akshat', 'Rohit'])
print(arr4)
print(type(arr4))
print(arr4.dtype)

['Naman' 'Akshat' 'Rohit']
<class 'numpy.ndarray'>
<U6


## Problem Statement ##
- The shape of an array is the number of elements in each dimension.
- NumPy arrays have an attribute called shape hat returns a tuple with each index having the number of correspoinding elements.

In [18]:
import numpy as np

array = np.array([[1,2,3,4],[5,6,7,8]])
print(array.shape)
array = np.array([1,2,3,4], ndmin=5)
print(array)
print('Shape of Array: ', array.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
Shape of Array:  (1, 1, 1, 1, 4)


## Reshape ##
- Reshape is when you change the number of rows and columns which gives a new view to an object.


In [21]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
a = a.reshape(3,2)
print(a)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [22]:
import numpy as np
a = np.array([[1,2,3,4,5,6]])
print(a)
a = a.reshape(2,3)
print(a)

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


## Basic Operations On Array ##
- arange is an array-valued version of the built-in python range function 

In [35]:
import numpy as np
a = np.arange(10)
print(a)
b = np.arange(1,10,2)
print(b)
a = np.linspace(0,6,6)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  1.2 2.4 3.6 4.8 6. ]


In [41]:
import numpy as np

x = np.array([(8,9,10),(11,12,13)])
y = np.array([(1,2,3),(4,5,6)])
print("x+y:",x + y)
print()
print("add:",np.add(x,y))
print()
print("subtract:",np.subtract(x,y))
print()
print("sum:",np.sum(x))
print()
print("sum axis-0:",np.sum(x, axis=0))
print()
print("sum axis-1:",np.sum(x, axis=1))


x+y: [[ 9 11 13]
 [15 17 19]]

add: [[ 9 11 13]
 [15 17 19]]

subtract: [[7 7 7]
 [7 7 7]]

sum: 63

sum axis-0: [19 21 23]

sum axis-1: [27 36]
